### ISSUE TITLE
Question: dynamic let

### ISSUE THREAD

**Issue by SRandazzo** [artsy/eidolon#394]
First, thank you Artsy Mobile Team for open sourcing this project, it's been extremely helpful!

I'm curious about the use of `dynamic let` properties in some of your models.

In the Artwork model, there are a few of these, and I can see elsewhere that you are RACObserving these properties, but if they are `let`, wont they never change unless the instance of the model itself changes? At which point I am curious, why not just observe the reference to the entire model?

Thanks again!

https://github.com/artsy/eidolon/blob/master/Kiosk/App/Models/Artwork.swift#L10

**Comment by ashfurrow** [comment]
That's a great question! I want to use `RACObserve` as much as possible to bind property values of models to property values of UI elements (labels, buttons, etc). As _much as possible_, I want to avoid setting a UI property based on a current model property, because that defeats the entire point of [FRP](http://reactivecocoa.io/philosophy.html). Some model properties are (currently) `let`, but they may not always be. It's very little overhead to mark them`dynamic` now and use `RACObserve`, and can save time, headaches, and bugs if they ever change to `var` in the future. 

Additionally, but having them `dynamic`, I can easily turn them into signals, which is useful for combining things together as signals. For example:

```swift
class Model: NSObject {
  dynamic var a = "Something"
  dynamic let b = "Something else"
}

let model = Model()

let signal = RACSignal.combine([RACObserve(model, "a"), RACObserve(model, "b")]).map { (tuple) -> AnyObject! in
  let a = tuple.first as String
  let b = tuple.second as String

  // Now I can use both properties *without* referring to the model object itself, avoiding problems with state changes and possible reference cycles
}

// I can now bind signal to something, or use it to create a new signal, or anything else. 
```

I haven't checked to see if that compiles, but you get the idea.

**Comment by alonecuzzo** [comment]
@ashfurrow 

I'd also like to echo @SRandazzo's thanks for the project.  I've learned a bunch from it from only looking at it for a little bit of time.

I was wondering what your feelings are about a completely immutable model.  I noticed that your models have a mix of `let` and `var` properties, but to achieve true model immutability one's model objects would have to be made up of completely variables set as `let` right?

What sort of factors do you take into account when deciding to make a property on a model object mutable or immutable?  Are you designing towards a completely immutable model state?  If you did eventually reach an immutable state, how would you approach updating immutable properties on model objects without getting bogged down in bulky Builder pattern code?

Thx!

**Comment by ashfurrow** [comment]
Thanks! I appreciate the kind words. 

I can only speak to our approach during eidolon's development. `let` properties are constant only if

- Their value never changes
- Their value is known at instantiation time

Lots of times, we get a subset of the complete data from our API and we fill it in later with more data. This probably isn't an ideal approach, and it's something we're aware of going forward. 

I would prefer having completely immutable models, but I don't think that's realistic on an iOS project because there are few resources or examples of how that would work. Instead, I want to head towards isolating the state of the models behind a [view model](https://github.com/artsy/eidolon/issues/333) so that controllers only have access to signals, not model state.

**Comment by ashfurrow** [comment]
Going to close this for now. If anyone would like clarification, please feel free to reopen it or open a new issue :tada:
