### ISSUE TITLE
Reserve state may not be up-to-date

### ISSUE THREAD

**Issue by dblock** [artsy/eidolon#456]
I've seen two kiosks display different reserve state and the correct current bid amount. Here's one of the screenshots (correct reserve state).

![img_1772](https://cloud.githubusercontent.com/assets/542335/7683546/d30ad84a-fd4d-11e4-87d5-35a94178d2ba.JPG)

Here's the other, taken from another kiosk at the same time.

![img_0015](https://cloud.githubusercontent.com/assets/542335/7707712/323b14c0-fe1f-11e4-9b19-3f66e14db3d6.png)

**Comment by ashfurrow** [comment]
This is very odd. The code that triggers an update to the current bid is intrinsically tied to the reserve state, and an update from the server would change both. 

What's more curious is that the first screenshot, the correct reserve state, is missing the "About Urs Fischer" paragraph, and has the estimated value repeated. Something funky is going on here.

**Comment by ashfurrow** [comment]
Ah, OK I think I see it. So the current bid label is updated whenever the highest bid changes. The label beneath it, with the reserve status, is updated whenever reserve status changes _or_ the _number of bids_ changes. 

@dblock Is it possible that the highest bid cents value of a sale artwork could be updated while the number of bids stays the same?

**Comment by ashfurrow** [comment]
So, the crux of it comes down to this: the highest bid changed and the top kiosk updated both reserve state and top bid. The bottom one only updated its highest bid. 

This makes no sense because the syncing code updates both these values. 

The only possibility I've been able to think of is related to [this line](https://github.com/artsy/eidolon/blob/77e53bec4a5ce06ae9cb93c261404333894eea28/Kiosk/Bid%20Fulfillment/BidCheckingNetworkModel.swift#L57), which updates the sale artwork model after a bid is placed. I'm going to look into the possibility that the `/api/v1/sale/\(auctionID)/sale_artwork/\(artworkID)` endpoint sends back a response that doesn't reflect a newly changed reserve status. This only makes sense if the bottom iPad was used to bid. 

@dblock I know this is from a while ago, but can you remember if the iPad on the bottom screenshot was used to bid? I'll look into trying to reproduce this.

**Comment by ashfurrow** [comment]
No, I just checked and the response returns the new, correct reserve status. 

I have no idea how this could have happened.

**Comment by dblock** [comment]
I don't have any good answers for your questions above :(

**Comment by ashfurrow** [comment]
No problem – thanks @dblock!

**Comment by joeyAghion** [comment]
@ashfurrow regarding "is it possible that the highest bid cents value of a sale artwork could be updated while the number of bids stays the same," I think the answer is yes.

After much back and forth, sales finally settled on that count meaning "number of distinct positions that have resulted in at least 1 bid" (implemented [here](https://github.com/artsy/gravity/blob/f353d490483c466df5704ac784fe304acd4414cd/app/models/domain/sale_artwork.rb#L87)). During the bidding iteration, 2 positions may actively be generating bids (increasing the highest bid amount) despite already being counted.

**Comment by ashfurrow** [comment]
Cool, ok then the #470 PR _should_ fix things then. Thanks Joey!
