### ISSUE TITLE
protocol Occupiable Unneeded

### ISSUE THREAD

**Issue by psophis** [artsy/eidolon#543]
CollectionType, which Array, Dictionary and Set conform to, [provides](https://developer.apple.com/library/prerelease/ios/documentation/Swift/Reference/Swift_CollectionType_Protocol/index.html#//apple_ref/swift/intfp/CollectionType/s:vPSs14CollectionType7isEmptySb) an isEmpty instance property. String has it's own [isEmpty](https://developer.apple.com/library/prerelease/ios/documentation/Swift/Reference/Swift_String_Structure/index.html#//apple_ref/swift/structp/String/s:vSS7isEmptySb) instance property.

https://github.com/artsy/eidolon/blob/9959ad473d49bf3ed2bcd5f897d0ff5d688f3d15/Kiosk/App/SwiftExtensions.swift#L37

**Comment by ashfurrow** [comment]
Not sure I follow... we need a way to make those types conform to the protocol so that our `Optional` extension has access to `isEmpty` and `isNotEmpty`. We don't need to provide an implementation of `isEmpty`, since as you point out it already exists. But it has to be defined in a protocol. 

I'd _like_ to have a protocol extension for `CollectionType` instead of for `Array`, `Dictionary`, and `Set`, but there's a bug in the Swift compiler that prevents that from working. 

Does that clear things up?

**Comment by psophis** [comment]
Yeah it does. I see what you mean.
