### ISSUE TITLE
Use of NSUserDefaults in testing

### ISSUE THREAD

**Issue by mathonsunday** [artsy/eidolon#580]
Ash had an example with a stubbedUserDefaults in his Emerging Best Practices talk so I was curious if it was used in eidolon. 

From looking at the code the approach is to not have a StubUserDefaults class. Instead I see NSUserDefaults(), rather than NSUserDefaults().sharedInstance(), used in the tests. 

For example in ArtsyProviderTests: 
```swift
// We fake our defaults to avoid actually hitting the network
defaults = NSUserDefaults()
defaults.setObject(NSDate.distantFuture(), forKey: "TokenExpiry")
defaults.setObject("Some key", forKey: "TokenKey")
```

This approach is very intriguing because it bypasses the work of writing and using a StubUserDefaults class. Why did you go with this approach? Do you have any examples of doing dependency injection with the NSUserDefaults() as the argument? 

One downside I see is that you have to set up your faked defaults for every test, but this is not something I'm doing with my StubbedUserDefaults anyway.

**Comment by orta** [comment]
The idea of stubbed user defaults might not be used in Eidolon extensively, but it's used in our other apps. Energy uses a [global NSUserDefaults](https://github.com/artsy/energy/blob/master/ArtsyFolio%20Tests/ARAppTestDelegate+Tests.m#L15) replacement provided by our testing components library [Forgeries](https://github.com/ashfurrow/Forgeries). This means no tests can ever access the dev's nsuserdefaults. However even with that, we still DI in our [defaults](https://github.com/artsy/energy/pull/160/files#diff-ccb0f75eb432b01bb050f87f9084bbe9R18) whenever we can.

DI-ing in the defaults like we do in Eidolon is generally what we do in all apps as a best practice to make it easy to test, especially anything that is Apple's domain and it's normal to access as a singleton. We have a problem with this on [Eigen](https://github.com/artsy/eigen/issues/533) where-in running the tests will log out the developer because it messes around with the real `NSUserDefaults` and `NSFileManager`. It's harder to make these changes once you've got hundreds of LOC though.

**Comment by ashfurrow** [comment]
Yeah, I hope I don't give you the impression that we have this all figured out 😅 We're learning as we go, and in our four iOS apps, you'll find four different approaches to almost everything. The reality is, sometimes we find a good practice in a new app but don't have time to go back and rewrite old apps to use it. Also, the stubbed user defaults was a handy example I used in that talk because most devs are familiar with it. 

I hope that helps, please let us know if we can clarify anything!
