### ISSUE TITLE
Is there a reason why Authenticated and Non authenticated networking requests cannot be in the same enum class? 

### ISSUE THREAD

**Issue by rlam3** [artsy/eidolon#631]
Is there a reason why Authenticated and Non authenticated networking requests cannot be in the same enum class? 

I understand that they work a bit differently... but why is it better to separate authenticated API vs non authenticated? 
I saw that there is a AuthorizedNetworking & Networking separated...  

Thanks!

**Comment by orta** [comment]
No reason technically, the reason we do it is so that that we have a strong conceptual separation.

Because this app is a kiosk, we want to strictly ensure that we never mix logged in users and logged out users. By having a separate auth'd object then we can dispose of that instead of juggling state logged in/out status on an individual networking model.

**Comment by ashfurrow** [comment]
@rlam3 thanks for the thoughtful question, I'm sure others will benefit from it. Going to close this, please feel free to re-open if you'd like clarification.
